export default interface JobPost{
    id: string,
    title: string,
    description: string,
    responsibilities: string,
    requirements: string,
    idealCandidate: string,
    categories: string[],
    opType: string,
    startDate: Date,
    endDate: Date,
    deadline: Date,
    location: string[],
    requiredSkills: string[]
    whenAndWhere: string,
    orgID: string,
    datePosted: Date,
    status: string,
    applicantsCount: number,
    viewsCount: number,
    orgName: string,
    logoUrl: string,
    isBookmarked: boolean,
    isRolling: boolean,
    questions: string,
    perksAndBenefits: string,
    createdAt: Date,
    updatedAt: Date,
    orgPrimaryPhone: string,
    orgEmail: string,
    average_rating: number,
    total_reviews: number

}

